//------------------------------------------------------------------------------
// <auto-generated>
//     Arquivo gerado automaticamente.
//     Alterações manuais aqui podem ser sobrescritas.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class RelatorioPedidos
{
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    protected global::System.Web.UI.WebControls.DropDownList ddlCliente;
    protected global::System.Web.UI.WebControls.TextBox txtDataInicio;
    protected global::System.Web.UI.WebControls.TextBox txtDataFim;
    protected global::System.Web.UI.WebControls.Button btnFiltrar;
    protected global::System.Web.UI.WebControls.Button btnExportPdf;
    protected global::Microsoft.Reporting.WebForms.ReportViewer ReportViewer1;
}
